//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetodoPago()
        {
            this.EncabezadoCompra = new HashSet<EncabezadoCompra>();
        }
    
        public int IdMetodo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<long> NumeroTarjeta { get; set; }
        public Nullable<int> CodigoSeguridad { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<int> IdTipoTarjeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncabezadoCompra> EncabezadoCompra { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
